name: CI
on:
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: ''
        required: false
        type: string
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
